### ISSUE TITLE
Newest commit does not compile.

### ISSUE THREAD

**Issue by danieltherealyang** [egraphs-good/extraction-gym#44]
@pavpanchekha 
commit eb0b157a1b6f502d87e4cad20a7bf34c52c0ddaa gets compile errors when running make. Reverting to previous commit removes these errors.

**Comment by pavpanchekha** [comment]
It would be convenient if you included the error message or any other relevant information in the bug report. I suppose the actual error message is this:

```
thread 'main' panicked at /Users/pavpan/.cargo/git/checkouts/egraph-serialize-cea10224aa6b7f0c/951b829/src/lib.rs:143:32:
No node with id NodeId("275")
```

Sounds like we committed bad JSONs.

**Comment by danieltherealyang** [comment]
Yeah that’s the same error I got.
